name: "todo[bot]"

on:
  push:
  pull_request:
    types: [opened, closed, synchronize]
  issues:
    types: [edited]
jobs:
  name: TODO
  runs-on: ubuntu-latest
  steps:
  - name: Context
    env: GITHUB_CONTEXT: ${{ toJson(github) }}
    run: /
      echo "$GITHUB_CONTEXT"
  - uses: kimusaku/todo@1.0.0
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
      LOG_LEVEL: DEBUG
